/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  sidebar1: [
    { type: 'autogenerated',  dirName: 'prerequisites' }
  ],
  sidebar2: [
    { type: 'autogenerated', dirName: 'bioinformatics' }
  ],
  sidebar3: [
    { type: 'autogenerated',  dirName: 'data_visualisation' }
  ],
  sidebar4: [
    { type: 'autogenerated', dirName: 'programming' }
  ],
  sidebar5: [
    { type: 'autogenerated', dirName: 'programming' }
  ],
  sidebar6: [
    { type: 'autogenerated', dirName: 'statistical_modelling' }
  ],
  sidebar7: [
    { type: 'autogenerated', dirName: 'population_genetics' }
  ],
  sidebar8: [
    { type: 'autogenerated', dirName: 'genome_wide_association_studies' }
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}]
  // But you can create a sidebar manually
};  

module.exports = sidebars;
