library(rmarkdown)
rmarkdown::render("R_basic_features_practical.rmd",output_format="word_document")
rmarkdown::render("R_basic_features_practical.rmd",output_format="md_document")
rmarkdown::render("R_basic_features_practical.rmd",output_format="pdf_document")
rmarkdown::render("R_introduction_to_basic_features.rmd",output_format="word_document")
rmarkdown::render("R_introduction_to_basic_features.rmd",output_format="md_document")
rmarkdown::render("R_introduction_to_basic_features.rmd",output_format="pdf_document")